#!/bin/bash

set -e

SCRIPT_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
source $SCRIPT_PATH/setup.bash

LL=${LOG_LEVEL:-info}
CONF=${CONFIG:-config.yaml}


sed -i "s/input-problem-description: rcll-pddl\/pddl-problem-template.pddl/input-problem-description: rcll-pddl\/pddl-problem-template-"${TEAM_COLOR,,}".pddl/g" $FAWKES_DIR/cfg/conf.d/pddl-robot-memory.yaml

if [[ $TEAM_COLOR == "MAGENTA" ]]
then
  COLOR_PREFIX=m
elif [[ $TEAM_COLOR == "CYAN" ]]
then
  COLOR_PREFIX=c
fi

sed -i "s/stargazer/mongodb-${COLOR_PREFIX}1/g;s/orinoco/mongodb-${COLOR_PREFIX}2/g;s/agamemnon/mongodb-${COLOR_PREFIX}3/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
sed -i "s/replica-set-members:.*/replica-set-members: \['mongodb-planner-${TEAM_COLOR,,}:27021','mongodb-${COLOR_PREFIX}1:27021','mongodb-${COLOR_PREFIX}2:27021','mongodb-${COLOR_PREFIX}3:27021'\]/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
sed -i "s/hosts:/hosts:\n        mongodb-planner-${TEAM_COLOR,,}: mongodb-planner-${TEAM_COLOR,,}:27021/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
sed -i "/plugins\/mongodb\/clients/,+50d" $FAWKES_DIR/cfg/gazsim-configurations/gazsim-config-override.yaml

sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template.pddl
sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template-cyan.pddl
sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template-magenta.pddl

echo "Waiting for MongoDB"
MAX_TRIES=${REFBOX_MONGODB_WAIT_MAX_TRIES:-50}
PERIOD=${REFBOX_MONGODB_WAIT_PERIOD:-1}
for h in "mongodb-planner-${TEAM_COLOR,,}" "mongodb-${COLOR_PREFIX}1" "mongodb-${COLOR_PREFIX}2"; do
  TRIES=0
  REFBOX_MONGODB_HOST=$h
  REFBOX_MONGODB_PORT=27021
  while ! curl -f -s "http://$REFBOX_MONGODB_HOST:$REFBOX_MONGODB_PORT" >/dev/null; do
    (( TRIES=TRIES+1 ))
    if (( $TRIES >= $MAX_TRIES )); then
      >&2 echo "Could not reach MongoDB $h after $TRIES tries, giving up"
      exit 21
    else
      sleep $PERIOD
    fi
  done
  (( TRIES=TRIES+1 ))
  echo "MongoDB $h reachable after $TRIES/$MAX_TRIES tries"
done

$FAWKES_DIR/bin/fawkes -c $CONF -L console -l $LL $META_PLUGIN || exit 42
